### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by SeigneurGhost** [MineWeb/Plugin-Intervention#13]
Bonjour,

Petite suggestion, (le plugin est très bien déjà) mais pour l'améliorer je pensais à cela
- Serait-il possible d'ajouter une colonne date lors de la planification des interventions et un type "Reporté"?

D'avance merci de votre lecture :)

**Comment by ByFow** [comment]
Bonjour,

Excellente suggestion, je vais m'y pencher :)
